
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SUBHAM
 */
public class DeleteFrame extends javax.swing.JFrame {
Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
    /**
     * Creates new form DeleteFrame
     */
    public DeleteFrame() {
        initComponents();
        conn =javaconnect.ConnecrDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        callno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("VAGRounded BT", 1, 24)); // NOI18N
        jLabel1.setText("DELETE  BOOKS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 200, 40));

        jLabel2.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel2.setText("Book Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        jLabel3.setText("CallNo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 80, -1));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 130, 30));

        callno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callnoActionPerformed(evt);
            }
        });
        getContentPane().add(callno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 130, 30));

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 110, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/100_Books_home_img.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 650, 250));

        setSize(new java.awt.Dimension(656, 287));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void callnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_callnoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                    String cd=null,df=null;
            String d=callno.getText();
             int flag=1;
        try{
            String sql="Select * from Books where CallNo=? and Name=? ";
            pst=conn.prepareStatement(sql);
             pst.setString(1,callno.getText());
            pst.setString(2,name.getText());
            //pst.setString(3,surname.getText());
            rs=pst.executeQuery();
            
            cd=name.getText();
            df=callno.getText();
           
            int b=1;int a=0;
                if(b==1)
                {
                     callno.setBackground(Color.red);
                   callno.setForeground(Color.white);
                    name.setBackground(Color.red);
                   name.setForeground(Color.white);
                    
                }
            if(rs.next())
            {
                flag=2;
                
            
                
                a=1;
                    callno.setBackground(Color.green);
                    callno.setForeground(Color.black);
                    name.setBackground(Color.green);
                    name.setForeground(Color.black);
                    //surname.setBackground(Color.green);
                    //surname.setForeground(Color.black);
                     JOptionPane.showMessageDialog(null, "All are correct");
                  
                
               
            }
              if(a==0)
                {
                    JOptionPane.showMessageDialog(null, "Any of these is not correct");
                    callno.setText("");
                    name.setText("");
              
                     callno.setBackground(Color.white);
                    callno.setForeground(Color.black);
                    name.setBackground(Color.white);
                    name.setForeground(Color.black);
                    //surname.setBackground(Color.white);
                    //surname.setForeground(Color.black);
                    
                }
        }
        catch(HeadlessException | SQLException e){
             JOptionPane.showMessageDialog(null, e);
        }finally{
          try{
              rs.close();
              pst.close();
          }
          catch(SQLException e)
          {
      }
        }      
        
        if(flag ==2)
        {
        int p=JOptionPane.showConfirmDialog(null,"Do you really want to delete?","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0){
        String sql="delete from Books where CallNo=? and Name=?";
        try{
        
        pst=conn.prepareStatement(sql);
        pst.setString(1,callno.getText());
        pst.setString(2,name.getText());
        pst.execute();
         JOptionPane.showMessageDialog(null,"Deleted");
         callno.setBackground(Color.white);
                   callno.setForeground(Color.white);
                    name.setBackground(Color.white);
                   name.setForeground(Color.white);
                    callno.setText("");
                    name.setText("");
         
     }
     catch(SQLException e){
         JOptionPane.showMessageDialog(null,e);
     }
        }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Not Successful");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AfterLibLogin ss= new AfterLibLogin();
        ss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField callno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
