/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
/**
 *
 * @author SUBHAM
 */
public class Issue extends javax.swing.JFrame {
Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
    /**
     * Creates new form Issue
     */
    public Issue() {
        initComponents();
         conn =javaconnect.ConnecrDb();
        Currentdate();
    }
public void Currentdate()
    {
    
    Calendar cal= new GregorianCalendar();
    int month = cal.get(Calendar.MONTH);
    int date = cal.get(Calendar.DAY_OF_MONTH);
    int year=cal.get(Calendar.YEAR);
   
       
    int sec = cal.get(Calendar.SECOND);
    int min = cal.get(Calendar.MINUTE);
    int hr=cal.get(Calendar.HOUR);
    Time_txt.setText(date+"/"+(month+1)+"/"+year +"  "+hr+"::"+(min)+"::"+sec+" ");

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        surname = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        callno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Time_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 153));
        jLabel1.setText("Book CallNo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 150, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 60, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Surname");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 82, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Contact");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 82, 20));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 80, -1));

        surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameActionPerformed(evt);
            }
        });
        getContentPane().add(surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 80, -1));

        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 80, -1));

        callno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callnoActionPerformed(evt);
            }
        });
        getContentPane().add(callno, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 80, -1));

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setText("Issue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 120, -1));

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, -1, -1));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Time_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Time_txtActionPerformed(evt);
            }
        });
        jPanel1.add(Time_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 230, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DATE-TIME ::");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 270, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Membaca.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-410, -10, 1210, 400));

        setSize(new java.awt.Dimension(800, 426));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void callnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_callnoActionPerformed

    private void Time_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Time_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Time_txtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                 Currentdate();
                 String ab=null,bc=null;
            String cd=null,df=null;
        try{
            String sql="Select * from LibraryMember where Name=? and Surname=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,name.getText());
            pst.setString(2,surname.getText());
            rs=pst.executeQuery();
            
            cd=name.getText();
            df=surname.getText();
            
            int b=1;int a=1;
                if(b==1)
                {
                    name.setBackground(Color.red);
                   name.setForeground(Color.white);
                    surname.setBackground(Color.red);
                   surname.setForeground(Color.white);
                }
            if(rs.next())
            {
                ab=name.getText();
                bc=surname.getText();
            
                 a=0;
                
                    name.setBackground(Color.green);
                    name.setForeground(Color.black);
                    surname.setBackground(Color.green);
                    surname.setForeground(Color.black);
                     JOptionPane.showMessageDialog(null, "Name and Surname are correct");
                  
                
                
            }
            if(a==1)
                {
                    JOptionPane.showMessageDialog(null, "Name and Surname are not correct");
                     callno.setText("");
                     contact.setText("");
                    name.setText("");
                    surname.setText("");
                     callno.setBackground(Color.white);
                    callno.setForeground(Color.black);
                    name.setBackground(Color.white);
                    name.setForeground(Color.black);
                    surname.setBackground(Color.white);
                    surname.setForeground(Color.black);
                }
        }
        catch(HeadlessException | SQLException e){
             JOptionPane.showMessageDialog(null, e);
        }finally{
          try{
              rs.close();
              pst.close();
          }
          catch(SQLException e)
          {
      }
        }
      try{
            
            if (ab.equals(cd)==true && bc.equals(df)==true)
            {
                
            String sql1= "select Id from Books where CallNo=?";
             
             pst=conn.prepareStatement(sql1);
            
            pst.setString(1, callno.getText());
             rs=pst.executeQuery();
             String a= null;
                         
             if(rs.next())
             {
                 int z=1;
                if(z==1)
                {
                    callno.setBackground(Color.green);
                   callno.setForeground(Color.black);
                    
                }
                 a=rs.getString("Id");
             
             
             
             String sql2= "Insert into IssuedBooks (BookID,CallNo,Stu_Name,Stu_Surname,Stu_Contact,Issued_date) values (?,?,?,?,?,?)";
            pst=conn.prepareStatement(sql2);
            pst.setString(1, a);
           
            pst.setString(2, callno.getText());
           
            pst.setString(3, name.getText());
            pst.setString(4, surname.getText());
            pst.setString(5, contact.getText());
            
            pst.setString(6, Time_txt.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Issued");
            
             }
             else
             {
                int b=1;
                if(b==1)
                {
                    callno.setBackground(Color.red);
                   callno.setForeground(Color.white);
                    
                } 
             }
            }
            if(ab.equals(cd)==false && bc.equals(df)==false)
            {
                int b=1;
                if(b==1)
                {
                    callno.setBackground(Color.red);
                   callno.setForeground(Color.white);
                    
                }
                 JOptionPane.showMessageDialog(null, "Not Issued");
            
             }
      }catch(HeadlessException | SQLException e){
             JOptionPane.showMessageDialog(null, e);
        }finally{
          try{
              rs.close();
              pst.close();
          }
          catch(SQLException e)
          {
      }
          
      }
            try{
            String sq="select Quantity,Issued from Books where CallNo=?";
            
             pst=conn.prepareStatement(sq);
             pst.setString(1, callno.getText());
             rs=pst.executeQuery();
             
             String c=null,d=null;
             
             if(rs.next())
             {
                 c=rs.getString("Quantity");
                 d=rs.getString("Issued");
                 
             }
             
             int x,y;
             x=Integer.parseInt(c);
             y=Integer.parseInt(d);
             
             
             String s =" UPDATE Books SET Quantity='"+(x-1)+"', Issued='"+(y+1)+"' where CallNo= '"+callno.getText()+"' ";
             pst=conn.prepareStatement(s);
             
             pst.execute();
                    callno.setText("");
                     contact.setText("");
                    name.setText("");
                    surname.setText("");
                     callno.setBackground(Color.white);
                    callno.setForeground(Color.black);
                    name.setBackground(Color.white);
                    name.setForeground(Color.black);
                    surname.setBackground(Color.white);
                    surname.setForeground(Color.black);
             
            
                    }
        catch(HeadlessException | SQLException e){
             JOptionPane.showMessageDialog(null, e);
        }finally{
          try{
              rs.close();
              pst.close();
          }
          catch(SQLException e)
          {
      }
          
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AfterLibLogin ss=new AfterLibLogin();
        ss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Issue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Time_txt;
    private javax.swing.JTextField callno;
    private javax.swing.JTextField contact;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField surname;
    // End of variables declaration//GEN-END:variables
}
