/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
/**
 *
 * @author SUBHAM
 */
public class UpdateBook extends javax.swing.JFrame {
Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
    /**
     * Creates new form UpdateBook
     */
    public UpdateBook() {
        initComponents();
         conn =javaconnect.ConnecrDb();
        Currentdate();

    }
    public void Currentdate()
    {
    
    Calendar cal= new GregorianCalendar();
    int month = cal.get(Calendar.MONTH);
    int date = cal.get(Calendar.DAY_OF_MONTH);
    int year=cal.get(Calendar.YEAR);
   
       
    int sec = cal.get(Calendar.SECOND);
    int min = cal.get(Calendar.MINUTE);
    int hr=cal.get(Calendar.HOUR);
    Time_txt.setText(date+"/"+(month+1)+"/"+year +"  "+hr+"::"+(min)+"::"+sec+" ");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        callno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        author = new javax.swing.JTextField();
        pub = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        q = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Time_txt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Book Call No ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));
        getContentPane().add(callno, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 130, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Name ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 130, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Author ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 70, -1));

        author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorActionPerformed(evt);
            }
        });
        getContentPane().add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 130, -1));

        pub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pubActionPerformed(evt);
            }
        });
        getContentPane().add(pub, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 130, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("Publisher ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Quantity ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 80, -1));

        q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qActionPerformed(evt);
            }
        });
        getContentPane().add(q, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 130, -1));

        jLabel6.setText("DATE-TIME ::");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        Time_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Time_txtActionPerformed(evt);
            }
        });
        getContentPane().add(Time_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 180, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 90, -1));

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 90, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pile-of-books_0.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -20, 620, 450));

        setSize(new java.awt.Dimension(535, 468));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorActionPerformed

    private void pubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pubActionPerformed

    private void qActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qActionPerformed

    private void Time_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Time_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Time_txtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AfterLibLogin ss=new AfterLibLogin();
        ss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String cd=null,df=null;
            String d=callno.getText();
             int flag=1;
        try{
            String sql="Select * from Books where CallNo=? and Name=? ";
            pst=conn.prepareStatement(sql);
             pst.setString(1,callno.getText());
            pst.setString(2,name.getText());
            //pst.setString(3,surname.getText());
            rs=pst.executeQuery();
            
            cd=name.getText();
            df=callno.getText();
           
            int b=1;int a=0;
                if(b==1)
                {
                     callno.setBackground(Color.red);
                   callno.setForeground(Color.white);
                    name.setBackground(Color.red);
                   name.setForeground(Color.white);
                    
                }
            if(rs.next())
            {
                flag=2;
                
            
                
                a=1;
                    callno.setBackground(Color.green);
                    callno.setForeground(Color.black);
                    name.setBackground(Color.green);
                    name.setForeground(Color.black);
                    //surname.setBackground(Color.green);
                    //surname.setForeground(Color.black);
                     JOptionPane.showMessageDialog(null, "All are correct");
                  
                
               
            }
              if(a==0)
                {
                    JOptionPane.showMessageDialog(null, "Any of these is not correct");
                    callno.setText("");
                    name.setText("");
              
                     callno.setBackground(Color.white);
                    callno.setForeground(Color.black);
                    name.setBackground(Color.white);
                    name.setForeground(Color.black);
                    //surname.setBackground(Color.white);
                    //surname.setForeground(Color.black);
                    
                }
        }
        catch(HeadlessException | SQLException e){
             JOptionPane.showMessageDialog(null, e);
        }finally{
          try{
              rs.close();
              pst.close();
          }
          catch(SQLException e)
          {
      }
        }      
        
            if(flag==2)
            {
                try{
               String add1=callno.getText();
               String add2= name.getText();
              
               String add3=author.getText();
               
               String add=pub.getText();
               
               String adr1= q.getText();
              
               String adr2=  Time_txt.getText(); 
               
               
               String sql="update Books set Name='"+add2+"',Author='"+add3+"',Publisher='"+add+"',Quantity='"+adr1+"',Added_Date='"+adr2+"' where CallNo='"+add1+"' ";
               pst=conn.prepareStatement(sql);
               pst.execute();

                JOptionPane.showMessageDialog(null,"Update Successful");
                callno.setText("");
                    name.setText("");
                    pub.setText("");
                    q.setText("");
                    author.setText("");
                     callno.setBackground(Color.white);
                    callno.setForeground(Color.black);
                    name.setBackground(Color.white);
                    name.setForeground(Color.black);
                   // name.setText("");
                    
          
        }
        catch(NumberFormatException | SQLException e)
        {
             JOptionPane.showMessageDialog(null,e);
        }
                finally{
          try{
              rs.close();
              pst.close();
          }
          catch(SQLException e)
          {
      }}
            }
            else
            {
                 JOptionPane.showMessageDialog(null,"Update Not Successful");
            }
                
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Time_txt;
    private javax.swing.JTextField author;
    private javax.swing.JTextField callno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pub;
    private javax.swing.JTextField q;
    // End of variables declaration//GEN-END:variables
}
